### ISSUE TITLE
Using pretrained models

### ISSUE THREAD

**Issue by Iqra840** [nicpopovic/FREDo#3]
Hello,

Thank you for your work. I tried using the pretrained models you made available on Drive, but am unsure of how to test them with custom data of my own. Is there a script I can use to run the model on my data?

**Comment by nicpopovic** [comment]
Hello, 

Looks like this issue slipped past me, sorry about that!
Thank you for your interest.

While it's been quite some time, for the sake of completeness:
The repo does not contain a script to easily run pretrained models on custom data.
