### ISSUE TITLE
Wrong cross-domain test files of raw data

### ISSUE THREAD

**Issue by phzh24** [nicpopovic/FREDo#4]
> If you are only interested in the raw data for the tasks, you can directly download sampled episodes here: https://drive.google.com/drive/folders/1PuJSJxqZP4ijxFSBZZ6Fmc0SgR2S8pYU?usp=sharing (test_episodes.zip [~120 MB DL, ~550MB on disk] + train_episodes_single.zip [~330MB DL, ~1.4GB on disk]+ train_episodes_schema.zip [~330MB DL, ~1.4GB on disk])

The two cross-domain test files in the Google Drive (`test_cross_domain_1_doc.json` and `test_cross_domain_3_doc.json`) were sampled from the `test_docred.json` file, which should have been sampled from the `test_sicerc.json`.

**Comment by nicpopovic** [comment]
Thank you for letting me know, I've updated the files!
